spring:
  application:
    name: task-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/gestao_tarefas
    username: root
    password: root
#    driver-class-name: org.postgresql.Driver
#    testWhileIdle: true
#    validationQuery: SELECT 1
  # JPA
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: '4Z^XrroxR@dWxqf$mTTKwW$!@#qGr4P'
    expiration: 86400000
    header: 'Authorization'
    prefix: 'Bearer'
    type: 'JWT'
    issuer: "bodegami-api"
    zone: 'America/Sao_Paulo'